name: Build (Windows)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [Release]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake)
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A x64

      - name: Build
        run: cmake --build build --config ${{ matrix.config }} --parallel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.config }}-binaries
          path: |
            build/bin/${{ matrix.config }}/UniversalBootstrap.exe
            build/bin/${{ matrix.config }}/UniversalTester.exe
          if-no-files-found: error

      - name: Get short SHA
        id: slug
        shell: pwsh
        run: |
          $sha7 = $env:GITHUB_SHA.Substring(0,7)
          "sha7=$sha7" >> $env:GITHUB_OUTPUT

      - name: Print short SHA
        run: echo "Short SHA: ${{ steps.slug.outputs.sha7 }}"

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.slug.outputs.sha7 }}
          files: |
            build/bin/${{ matrix.config }}/UniversalBootstrap.exe
            build/bin/${{ matrix.config }}/UniversalTester.exe